name: Dotnet Authentication Azure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['authentication/dotnet/azure/**', '.github/workflows/**', 'scripts']
  pull_request:
    paths: ['authentication/dotnet/azure/**', '.github/workflows/**', 'scripts']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_URL: https://nuget.pkg.github.com/microsoft/index.json
      relativePath: ./authentication/dotnet/azure
      solutionName: Microsoft.Kiota.Authentication.Azure.sln
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Add NuGet kiota source
        # NOTE: Password encryption is not supported for the linux platform (Encryption is only supported on Windows platforms.)
        run: |
          dotnet nuget add source ${{env.NUGET_URL}} -n github -u ${{secrets.PUBLISH_GH_USERNAME}} -p ${{secrets.PUBLISH_GH_TOKEN}} --store-password-in-clear-text
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
        working-directory: ${{ env.relativePath }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Release
        working-directory: ${{ env.relativePath }}
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
        working-directory: ${{ env.relativePath }}
      - name: Publish
        run: dotnet publish ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Pack
        run: dotnet pack ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage
          path: |
            ${{ env.relativePath }}/Microsoft.Kiota.Authentication.Azure.Tests/TestResults  
      - name: Upload Nuget package
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/src/bin/Release/*.nupkg
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: dotnet nuget push "*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/microsoft/index.json -k ${{ secrets.PUBLISH_GH_TOKEN }}
