name: Dotnet HTTP HTTPClient

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['http/dotnet/httpclient/**', '.github/workflows/**', 'scripts']
  pull_request:
    paths: ['http/dotnet/httpclient/**', '.github/workflows/**', 'scripts']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./http/dotnet/httpclient
      solutionName: Microsoft.Kiota.Http.HttpClientLibrary.sln
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.x
      - run: ./scripts/updateNugetCredentials.ps1 -username "${{ secrets.PUBLISH_GH_USERNAME }}" -apiToken "${{ secrets.PUBLISH_GH_TOKEN }}" -nugetFileAbsolutePath "${{ env.relativePath }}/nuget.config"
        shell: pwsh
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
        working-directory: ${{ env.relativePath }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Release
        working-directory: ${{ env.relativePath }}
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
        working-directory: ${{ env.relativePath }}
      - name: Publish
        run: dotnet publish ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Pack
        run: dotnet pack ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: codeCoverage
          path: |
            ${{ env.relativePath }}/Microsoft.Kiota.Http.HttpClientLibrary.Tests/TestResults  
      - name: Upload Nuget package
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/src/bin/Release/*.nupkg
      - run: rm ${{ env.relativePath }}/nuget.config
        if: always()
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.0.x
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: dotnet nuget push "*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/microsoft/index.json -k ${{ secrets.PUBLISH_GH_TOKEN }}
